
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/product-service?useSSL=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: product-service

server:
  port: 8181
